framing_map = {
    "Economic": "Economic",
    "External_regulation_and_reputation": "External regulation and reputation",
    "Capacity_and_resources": "Capacity and resources",
    "Political": "Political",
    "Security_and_defense": "Security and defense",
    "Quality_of_life": "Quality of life",
    "Policy_prescription_and_evaluation": "Policy prescription and evaluation",
    "Legality_Constitutionality_and_jurisprudence": "Legality Constitutionality and jurisprudence",
    "Cultural_identity": "Cultural identity",
    "Fairness_and_equality": "Fairness and equality",
    "Crime_and_punishment": "Crime and punishment",
    "Health_and_safety": "Health and safety",
    "Public_opinion": "Public opinion",
    "Morality": "Morality",
}

persuasion_map = {
    "labels.Appeal_to_Authority": "Appeal to Authority",
    "labels.Appeal_to_Popularity": "Appeal to Popularity",
    "labels.Appeal_to_Values": "Appeal to Values",
    "labels.Appeal_to_Fear-Prejudice": "Appeal to Fear-Prejudice",
    "labels.Flag_Waving": "Flag Waving",
    "labels.Causal_Oversimplification": "Causal Oversimplification",
    "labels.False_Dilemma-No_Choice": "False Dilemma-No Choice",
    "labels.Consequential_Oversimplification": "Consequential Oversimplification",
    "labels.Straw_Man": "Straw Man",
    "labels.Red_Herring": "Red Herring",
    "labels.Whataboutism": "Whataboutism",
    "labels.Slogans": "Slogans",
    "labels.Appeal_to_Time": "Appeal to Time",
    "labels.Conversation_Killer": "Conversation Killer",
    "labels.Loaded_Language": "Loaded Language",
    "labels.Repetition": "Repetition",
    "labels.Exaggeration-Minimisation": "Exaggeration-Minimisation",
    "labels.Obfuscation-Vagueness-Confusion": "Obfuscation-Vagueness-Confusion",
    "labels.Name_Calling-Labeling": "Name Calling-Labeling",
    "labels.Doubt": "Doubt",
    "labels.Guilt_by_Association": "Guilt by Association",
    "labels.Appeal_to_Hypocrisy": "Appeal to Hypocrisy",
    "labels.Questioning_the_Reputation": "Questioning the Reputation",
}
